<?php if(!empty($this->arrproduct)){?>
<div class="page sidebar-page container" style="margin-bottom: 10px;">
	<div class="page-tittle container">
		<div class="">
			<div class="row">
				<h3 class="col-sm-6 text-left"><?php echo $this->arrproduct['pro_name'];?></h3>
			</div>
		</div>
	</div>
</div>
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 main-content product-page">
				<div class="media">
					<div class="row">
						<img src="<?php echo $this->arrproduct['pro_image'];?>" alt="" class="img_pro">
						<p><?php echo $this->arrproduct['pro_desc'];?></p>
					</div>
				</div>
			</div>
			<?php include_once('../application/layouts/scripts/leftsidebar.phtml');?>
		</div>
	</div>
</div>
<?php }?>
