<div class="page sidebar-page container" style="margin-bottom: 10px;">
	<div class="page-tittle container">
		<div class="">
			<div class="row">
				<h3 class="col-sm-6 text-left">Sản phẩm</h3>
			</div>
		</div>
	</div>
</div>
<div class="content">
	<div class="container">
		<div class="row">
			<div class="col-lg-9 main-content product-grid">
				<div id="display-result" class="row">
					<?php if(!empty($this->arrproduct)){?>
					<?php foreach ($this->arrproduct as $row){?>
					<div class="col-sm-4 item">
						<div class="inner">
							<div class="product-image">
								<a href="/frontend/product/detail/pro_id/<?php echo $row['pro_id']?>">
									<img src="<?php echo $row['pro_image'];?>"></a>
							</div>
							<div class="product-name">
								<a href="/frontend/product/detail/pro_id/<?php echo $row['pro_id']?>">
									<?php echo $row['pro_name']?></a>
							</div>
						</div>
					</div>
					<?php }?>
					<div class="col-md-12 col-xs-12 col-sm-12 text-center">
						<div id="pg">
							<div class="paging">
								<div class="dataTables_paginate paging_bootstrap pagination">
									<?php echo $this->paging;?>
								</div>
							</div>
						</div>
					</div>
					<?php }?>
				</div>
			</div>
			<?php include_once('../application/layouts/scripts/leftsidebar.phtml');?>
		</div>
	</div>
</div>
<script type="text/javascript" src="/templates/js/form/frontend/product.js"></script>