<?php
$uri = $this->serverUrl();
?>
<style>
    .icon-header{
        height: 60px !important;
    }
    .table-bordered th{
        background: rgba(61, 61, 61, 0.81);
        color: #FFFFFF;
    }
    .title-label{
        margin-left: -30px;
        font-weight: bold;
    }
</style>
<div class="page-content-admin" style="    padding-left: 75px;">

    <div class="title-label">Spin Information</div>
    <div class="row col-md-12">
        <div class="col-md-6">
            <div class="panel panel-blue">
                <div class="panel-body pan">
                    <!-- REPORT AREA-->
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th width="30%">Transaction Type</th>
                                <th width="20%">Duration (days)</th>
                                <th width="20%">Sent (BTC)</th>
                                <th width="">Recived (BTC)</th>
                            </tr>
                            <?php if(isset($this->listfee) && !empty($this->listfee)){ ?>
                                <?php foreach ($this->listfee as $row){ ?>
                                    <tr>
                                        <td width="30%"><?php echo isset($row['transaction_typ'])? $row['transaction_typ']:0;?></td>
                                        <td width="20%">
                                            <?php echo isset($row['duration'])? $row['duration']:0;?>  days
                                        </td>
                                        <td width="20%">
                                            <?php echo isset($row['amount'])? $row['amount']:0;?>  BTC
                                        </td>
                                        <td width="40%">
                                            <?php echo isset($row['recived'])? $row['recived']:0;?>  BTC
                                        </td>
                                    </tr>
                                <?php } ?>
                            <?php } ?>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>