<?php
$uri = $this->serverUrl();
?>
<style>
    .icon-header{
        height: 60px !important;
    }
    .table-bordered th{
        background: rgba(61, 61, 61, 0.81);
        color: #FFFFFF;
    }


</style>
<div class="page-content-admin" style="    padding-left: 75px;">

    <div class="row col-md-12">
        <div class="col-md-6">
            <div class="panel panel-blue">
                <div class="panel-body pan">
                    <form method="post" action="profile">

                        <div class="table-responsive">
                            <table class="table table-bordered">
                                <tbody>
                                <tr>
                                    <td width="60%">Total Waiting Transaction</td>
                                    <td width="40%">
                                        <?php echo isset($this->data['total_waiting'])? 1*$this->data['total_waiting']:0;?>  Transactions
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Total Waiting Transaction</td>
                                    <td width="40%">
                                        <?php echo isset($this->data['total_waiting'])? 1*$this->data['total_waiting']:0;?>  Transactions
                                    </td>
                                </tr>

                                <tr>
                                    <td width="60%">Total Confirmed Transaction</td>
                                    <td width="40%">
                                        <?php echo isset($this->data['total_confrimed'])? 1*$this->data['total_confrimed']:0;?>  Transactions
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Total PH Transaction</td>
                                    <td width="40%">
                                        <?php echo isset($this->data['total_PH'])? 1*$this->data['total_PH']:0;?>  Transactions
                                    </td>
                                </tr>

                                </tbody>
                            </table>

                        </div></form>
                </div>
            </div>
        </div>


    </div>
</div>