<div class="page-content">
    <div class="row">



        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">Send Ticket Support</div>
                <div class="panel-body pan">



                    <form method="post" action="support">

                        <div class="table-responsive">
                            <table class="table table-hover table-bordered">


                                <tbody>


                                <tr>
                                    <td colspan="2">

                                    </td>
                                </tr>




                                <tr>
                                    <td style="padding-left:20px;">UserName</td>
                                    <td><input type="text" class="form-control" name="username" required="" value="minh thien" readonly=""></td>
                                </tr>
                                <tr>
                                    <td style="padding-left:20px;">Email</td>
                                    <td><input type="text" class="form-control" name="email" required="" value="nguyenthanhuet@gmail.com" readonly=""></td>
                                </tr>
                                <tr>
                                    <td style="padding-left:20px;">Subject</td>
                                    <td><input type="text" class="form-control" name="subject" required="" placeholder="ex : kennedy20"></td>
                                </tr>


                                <tr>
                                    <td style="padding-left:20px;">Messages</td>
                                    <td><textarea type="text" class="form-control" required="" name="comments"></textarea></td>
                                </tr>

                                <tr>
                                    <td colspan="2" style="text-align:center;">
                                        <button type="submit" class="btn btn-info">Send Ticket
                                        </button></td>
                                </tr>
                                </tbody>
                            </table>

                        </div></form>
                </div>
            </div>
        </div></div>

</div>