<div class="page-content">

    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-blue">
                <div class="panel-heading">MY INVEST REPORT</div>
                <div class="panel-body pan">



                    <form method="post" action="profile">

                        <div class="table-responsive">
                            <table class="table table-hover table-bordered">
                                <tbody>

                                <tr>
                                    <td width="60%">Total INVEST</td>
                                    <td width="40%">
                                        1  Transaction/s
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="2"></td>
                                </tr>

                                <tr>
                                    <td width="60%">Pending INVEST Transaction/s</td>
                                    <td width="40%">
                                        1  Transaction/s
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Success INVEST Transaction/s</td>
                                    <td width="40%">
                                        0  Transaction/s
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Problem INVEST Transaction/s</td>
                                    <td width="40%">
                                        1  Transaction/s
                                    </td>
                                </tr>

                                <tr>
                                    <td colspan="2"></td>
                                </tr>


                                <tr>
                                    <td width="60%">Total INVEST Amount</td>
                                    <td width="40%">
                                        USD 110 </td>
                                </tr>

                                <tr>
                                    <td colspan="2"></td>
                                </tr>

                                <tr>
                                    <td width="60%">Pending INVEST Amount</td>
                                    <td width="40%">
                                        USD 110 </td>
                                </tr>
                                <tr>
                                    <td width="60%">Success INVEST Amount</td>
                                    <td width="40%">
                                        USD 0 </td>
                                </tr>
                                <tr>
                                    <td width="60%">Problem INVEST Amount</td>
                                    <td width="40%">
                                        USD 110 </td>
                                </tr>

                                </tbody>
                            </table>

                        </div></form>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <div class="panel panel-blue">
                <div class="panel-heading">MY GET PROFIT REPORT</div>
                <div class="panel-body pan">



                    <form method="post" action="profile">

                        <div class="table-responsive">
                            <table class="table table-hover table-bordered">
                                <tbody>

                                <tr>
                                    <td width="60%">Total GET PROFIT</td>
                                    <td width="40%">
                                        0  Transaction/s
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                </tr>

                                <tr>
                                    <td width="60%">Pending GET PROFIT Transaction/s</td>
                                    <td width="40%">
                                        0  Transaction/s
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Success GET PROFIT Transaction/s</td>
                                    <td width="40%">
                                        0  Transaction/s
                                    </td>
                                </tr>
                                <tr>
                                    <td width="60%">Problem GET PROFIT Transaction/s</td>
                                    <td width="40%">
                                        0  Transaction/s
                                    </td>
                                </tr>


                                <tr>
                                    <td colspan="2"></td>
                                </tr>


                                <tr>
                                    <td width="60%">Total GET PROFIT Amount</td>
                                    <td width="40%">
                                        USD 0 </td>
                                </tr>
                                <tr>
                                    <td colspan="2"></td>
                                </tr>

                                <tr>
                                    <td width="60%">Pending GET PROFIT Amount</td>
                                    <td width="40%">
                                        USD 0 </td>
                                </tr>
                                <tr>
                                    <td width="60%">Success GET PROFIT Amount</td>
                                    <td width="40%">
                                        USD 0 </td>
                                </tr>
                                <tr>
                                    <td width="60%">Problem GET PROFIT Amount</td>
                                    <td width="40%">
                                        USD 0 </td>
                                </tr>

                                </tbody>
                            </table>

                        </div></form>
                </div>
            </div>
        </div>
    </div>
    <br><br>

</div>